name: Build Docker image

on:
  push:
    branches: [ "Actions_test" ]
  pull_request:
    branches: [ "Actions_test" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag graphql-framework:$(date +%s)
