name: Run Unit Tests

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Build and Run Docker Container
        run: |
          docker build -t graphql_framework -f Dockerfile_github_actions .
          docker run graphql_framework sh -c "gradlew test -PunitTest"
